### PR TITLE
Compile with GHC 8

### PR DESCRIPTION
**Pull request by charles-cooper**
Some updates to the use of GHC 8's Generics API had to be made (cf. https://ghc.haskell.org/trac/ghc/wiki/Migration/8.0).

Fixes https://github.com/alevy/postgresql-orm/issues/17

### CODE REVIEW

**Comment by alevy** [comment]
This, overall seems great to me, However, the build is complaining about `AllowAmbiguousTypes`. In ernest, I haven't heard of that extension, but if we go forward using it, let's at least make the compiler satisfied :).

**Comment by charles-cooper** [comment]
That's interesting. It was building fine for me locally using GHC 8 and GHC 7.10 .. looks like travis is using 7.6 somehow. But AllowAmbiguousTypes should have been around in GHC 7.6. Will look into this when I have more time

**Comment by alevy** [comment]
@charles-cooper this last one seems to be a winner :+1: 
Can you just clean up the history a bit? Happy for you to override my commits.

**Comment by charles-cooper** [comment]
Yep, do you mind if i force push?

**Comment by alevy** [comment]
No not at all... it's your branch!

**Comment by charles-cooper** [comment]
@alevy how do those commits look?

**Comment by alevy** [comment]
@charles-cooper yep! awesome!

**Comment by alevy** [comment]
I'll do a version bump and push to hackage. Do you think this warrants a major(ish) version bump (i.e. to `0.5.0`)?

**Comment by charles-cooper** [comment]
well, it's still compiling with ghc 7.8 so it's not breaking that. it might break earlier versions. my thought would be to bump to 0.5.0 :)

**Pull request merged**
